name: React CI

on:
  push:
    branches:
      - newsapp-api
  pull_request:
    branches:
      - newsapp-api

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Run Tests
      run: npm test -- --watchAll=false